<?php
namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class TestSecurityController extends WebTestCase
{

    /**
     * @var
     */
    private $client;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->client = static::createClient();

    }

    /**
     * @test
     * testing status code and test route
     */
    public function testShowLogin()
    {
        $this->client->request('GET', '/login');
        $this->assertEquals('200', $this->client->getResponse()->getStatusCode());
        $this->assertTrue($this->client->getResponse->isSuccessful());
    }

    /**
     * @test
     * testing login (email => valid email && password => bcrypt(valid password)
     */
    public function testLogin()
    {

    }

    /**
     * @test
     * testing status code and test route
     */
    public function testShowRegister()
    {
        $this->client->request('GET', '/register');
        $this->assertEquals('200', $this->client->getResponse()->getStatusCode());
        $this->assertTrue($this->client->getResponse->isSuccessful());
    }

    /**
     * @test
     * testing new inserting user
     */
    public function testRegister()
    {

    }
}